services:
  serverapi:
    build: 
      context: .
      dockerfile: Dockerfile.serverAPI
    ports:
      - "8081:8081"
    container_name: serverapi
    restart: unless-stopped
  clientapi:
    build: 
      context: .
      dockerfile: Dockerfile.clientAPI
    ports:
      - "8091:8091"
    container_name: clientapi
    restart: unless-stopped
