version: '3.8'

services:
  server:
    build: .
    container_name: protobuf_server
    ports:
      - "8082:8082"
    command: ./server
    volumes:
      - .:/app

  client:
    build: .
    container_name: protobuf_client
    depends_on:
      - server
    command: ./client -h server -p 8082 -t REGISTRATION_REQUEST -i 1
    volumes:
      - .:/app
