services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.serverAPI
    container_name: rest_api_server
    ports:
      - "8081:8081"

  client:
    build:
      context: .
      dockerfile: Dockerfile.clientAPI
    container_name: rest_api_client
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8081  # Container networking
